return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "stylua",
        "lua-language-server",
        "shfmt",
        "flake8",
        "goimports",
        "gopls",
        "eslint-lsp",
        "json-lsp",
        "prettierd",
        "typescript-language-server",
        "html-lsp",
        "css-lsp",
        "bash-language-server",
        "python-lsp-server",
        "jdtls",
        "google-java-format",
        "rust-analyzer",
        "rustfmt",
        "helm-ls",
        "erlang-ls",
      },
    },
  },
  {
    "simrat39/symbols-outline.nvim",
    cmd = "SymbolsOutline",
    keys = { { "<leader>cs", "<cmd>SymbolsOutline<cr>", desc = "Symbols Outline" } },
    config = true,
  },
}
